debug: false

logging:
    
    level:
        org.springframework: WARN
        br.com.wagnersoft.babilonia: INFO

management:
    
    endpoints:
        web:
            exposure:
                include: health, info, mappings
                
    endpoint:
        health:
            show-details: always        
        mappings:
            enabled: true
        
server:

    port: 80

    http2:
        enabled: true
        
    servlet:
        context-path: /babilonia/api
        compression:
            enabled: true
            min-response-size: 1KB
        
    ssl:
        enabled: false
        key-store: ""          #keystore.p12
        key-store-password: "" #123
        #keyStoreType: PKCS12
        #keyAlias: babilonia

spring:

    profiles:
        active: dev

    application:
        name: babilonia

    datasource:
        url: jdbc:h2:mem:babilonia;INIT=CREATE SCHEMA IF NOT EXISTS babilonia;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password: 123
        hikari:
          minimum-idle: 1
          maximum-pool-size: 10
          idle-timeout: 600000       # ms (10 min)
          max-lifetime: 1800000      # ms (30 min)
          connection-timeout: 30000  # ms (30 s)
          pool-name: BabiloniaHikariPool
          initialization-fail-timeout: 1

    jpa:
        show-sql: false
        defer-datasource-initialization: true
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
            dialect: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    batch_size: 500
                order_inserts: true
                
    jdbc:
        template:
            query-timeout: 30

    mvc:
        pathmatch:
            matching-strategy: path-pattern-parser #ant_path_matcher

    h2:
        console:
            enabled: true

springdoc:
    
    packagesToScan: br.com.wagnersoft.babilonia.controller
    
    pathsToMatch: /v1/**

    api-docs:
        enabled: true
    
    swagger-ui:
        enabled: true
        tags-sorter: alpha
        operations-sorter: alpha
        persist-authorization: true
        doc-expansion: none
        default-models-expand-depth: 1
        filter: true
        # try-it-out-enabled: false
