# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/setup-java.yml
    with: {}
    secrets: inherit
    steps:
      - run: mvn -B package -DskipTests

  test:
    uses: ./.github/workflows/setup-java.yml
    needs: build
    secrets: inherit
    steps:
      - run: mvn -B verify jacoco:report
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco
          path: target/site/jacoco
          if-no-files-found: ignore  

  javadocs:
    uses: ./.github/workflows/setup-java.yml
    needs: build
    secrets: inherit
    steps:
      - run: mvn -B compile javadoc:javadoc
      - uses: actions/upload-artifact@v4
        with:
          name: javadocs
          path: target/site/apidocs
          if-no-files-found: ignore

  checkstyle:
    uses: ./.github/workflows/setup-java.yml
    needs: build
    secrets: inherit
    steps:
      - run: mvn -B checkstyle:checkstyle
      - uses: actions/upload-artifact@v4
        with:
          name: checkstyle
          path: target/site/checkstyle.html
          if-no-files-found: ignore  

  spotbugs:
    uses: ./.github/workflows/setup-java.yml
    needs: build
    secrets: inherit
    steps:
      - run: mvn -B spotbugs:spotbugs
      - uses: actions/upload-artifact@v4
        with:
          name: spotbugs
          path: target/spotbugs.html
          if-no-files-found: ignore

  deployment:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Optional, but recommended if using v4+ 

    runs-on: ubuntu-latest
    needs: [test, javadocs, checkstyle, spotbugs]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Download Jacoco
        uses: actions/download-artifact@v4
        with:
          name: jacoco
          path: quality/coverage
          if-no-files-found: ignore

      - name: Download Javadocs
        uses: actions/download-artifact@v4
        with:
          name: javadocs
          path: quality/javadocs
          if-no-files-found: ignore

      - name: Download Checkstyle
        uses: actions/download-artifact@v4
        with:
          name: checkstyle
          path: quality
          if-no-files-found: ignore

#      - name: Download SpotBugs
#        uses: actions/download-artifact@v4
#        with:
#          name: spotbugs
#          path: quality
#          if-no-files-found: ignore

      - name: Create index.html
        run: |
          cat <<'EOF' > quality/index.html
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
            <meta charset="UTF-8">
            <title>Portal de Qualidade - Babilonia</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous"> 
          </head>
          <body class="m-5">
            <h1>Portal de Qualidade do Projeto Babilonia</h1>
            <hr>
            <h2>Relatórios gerados automaticamente:</h2>
            <ul>
              <li>📊 <a href="coverage/index.html">Cobertura de Testes (Jacoco)</a></li>
              <li>📚 <a href="javadocs/index.html">Documentação (Javadocs)</a></li>
              <li>✅ <a href="checkstyle.html">Relatório de Estilo (Checkstyle)</a></li>
              <li>🐞 <a href="spotbugs.html">Relatório de Bugs (SpotBugs)</a></li>
            </ul>
            <hr>
            <p>(c)2026 WagnerSoft IT Solutions.</p>
          </body>
          </html>
          EOF

      - uses: actions/upload-pages-artifact@v3
        with:
          path: quality

      - uses: actions/deploy-pages@v5
        id: deployment
